### ISSUE TITLE
Invalid regexp group on Firefox

### ISSUE THREAD

**Issue by pchaigno** [Alhadis/Harvester#12]
When I try to paste the Harvester's code in the Firefox debug console, I get a `SyntaxError: invalid regexp group` error. It still works fine with Chromium. I've been using Harvester with Firefox since the first time I used it so the error was probably added recently. I'm going to investigate...

**Comment by pchaigno** [comment]
The error was added in 2485145d8e9a75454227ab261448159aa75d07e8.

**Comment by pchaigno** [comment]
...and comes from [the `/(?<!(?:^|\s)NOT)(?<=\S+)(?=\s+)/` regexp](https://github.com/Alhadis/Harvester/blob/a566c7818c9af0185ca4cff18f5fa685aca6abdf/harvester.js#L74).

**Comment by pchaigno** [comment]
It looks like you can't use lookbehind expressions with the regex engine used for Firefox's split function.

**Comment by Alhadis** [comment]
Wait, Firefox is lagging behind? 😕 Good grief, I assumed they'd be up-to-date with [ES2018](http://kangax.github.io/compat-table/es2016plus/#test-RegExp_Lookbehind_Assertions)...

**Comment by pchaigno** [comment]
Whoa! Thanks for the fix! Sorry for adding that extra complexity :/

**Comment by Alhadis** [comment]
Hah. No problem. 😉 The code I just added was [something](https://github.com/Alhadis/Utils/blob/7a5e93369a6096d39666659ca71c25cc96f1ec56/lib/text.mjs#L188-L227) I prepared much, much earlier.

**Comment by pchaigno** [comment]
Such precognition!
