### ISSUE TITLE
Instructions to download files

### ISSUE THREAD

**Issue by pchaigno** [Alhadis/Harvester#5]
The instructions to download the files in the README download the HTML pages, not the actual files. Not sure whether that was the intention.

I made the following command to download the raw files:
```bash
for f in $(cat urls.txt); do dir=$(echo $f | sed 's#https://github.com/##' | sed -r 's#/blob/\w+##' | sed 's#[^/]*\.[hH]$##'); mkdir -p $dir; wget -q --directory-prefix=$dir $(echo $f | sed 's#/blob/#/raw/#'); done
```
or with correct indentation:
```bash
for f in $(cat urls.txt); do
  dir=$(echo $f | sed 's#https://github.com/##' | sed -r 's#/blob/\w+##' | sed 's#[^/]*\.[hH]$##')
  mkdir -p $dir
  wget -q --directory-prefix=$dir $(echo $f | sed 's#/blob/#/raw/#')
done
```

**Comment by Alhadis** [comment]
Which instructions? The example download snippets at the bottom of the README?

If they're not working, it's because they were told to download HTML files instead of what they were meant to redirect to. I'm having a closer look now.

**Comment by pchaigno** [comment]
> Which instructions? The example download snippets at the bottom of the README?

Yep, [these](https://github.com/Alhadis/Harvester#downloading-files).

**Comment by Alhadis** [comment]
Could you copy+paste me the first 5 or so URLs that were being fed to the scripts?

**Comment by pchaigno** [comment]
```
$ head urls.txt 
https://github.com/96189/xteam/blob/0607224ac72be578aacf04abb0cf94c70e5256e5/OpenSource/Redis/redis-stable/src/server.h
https://github.com/aarond10/rawdishfs/blob/ea414a1778eab3b05477f5b554576491022c9c7b/src/blockstore/blockstore.h
https://github.com/aarond10/rawdishfs/blob/ea414a1778eab3b05477f5b554576491022c9c7b/src/blockstore/blockstore_daemon.h
https://github.com/aarond10/rawdishfs/blob/ea414a1778eab3b05477f5b554576491022c9c7b/src/blockstore/fileblockstore.h
https://github.com/aarond10/rawdishfs/blob/ea414a1778eab3b05477f5b554576491022c9c7b/src/blockstore/remoteblockstore.h
https://github.com/aarond10/rawdishfs/blob/ea414a1778eab3b05477f5b554576491022c9c7b/src/rpc/rpc.h
https://github.com/aarond10/rawdishfs/blob/ea414a1778eab3b05477f5b554576491022c9c7b/src/rpc/service_node.h
https://github.com/aarond10/rawdishfs/blob/ea414a1778eab3b05477f5b554576491022c9c7b/src/util/bloomfilter.h
https://github.com/aarond10/rawdishfs/blob/ea414a1778eab3b05477f5b554576491022c9c7b/src/util/lrucache.h
https://github.com/aarond10/rawdishfs/blob/ea414a1778eab3b05477f5b554576491022c9c7b/src/util/url.h
```

**Comment by Alhadis** [comment]
Ugh, they're supposed to have `?raw=1` added to the end (which redirects to the "raw" code-file). Must've accidentally trodden on it during the last refactor... 😓 

Am fixing...

**Comment by Alhadis** [comment]
Alright, so what I've done this time is convert the `github.com` URLs to `raw.githubusercontent.com` when results are being harvested (getting copied to the clipboard). Previously they were copied with `?raw=1` tacked on the end, resulting in a redirect. Guessing not all download tools will treat those the same...

The `?url=1` was also included in the filenames of the downloaded files, BTW. Yuck.

**Comment by pchaigno** [comment]
Great! Thanks a lot @Alhadis!
