### ISSUE TITLE
Avatars downloaded during scraping

### ISSUE THREAD

**Issue by pchaigno** [Alhadis/Harvester#7]
I wasn't expecting XHR to download images with HTML pages, but it looks like it does download avatars while scraping search results:
![harvester](https://user-images.githubusercontent.com/1764210/43689655-220c6d74-98fe-11e8-90ac-bfadef434323.png)

Is this the expected behavior? It doesn't slow down the scraping anyway, but it does amount to a fair bit of content.

**Comment by Alhadis** [comment]
Ah damn, you're right. That wasn't supposed to happen. 🤔

Fixed in b96508e.

**Comment by pchaigno** [comment]
Good to know I haven't forgot everything about XHR :-)

If I understand correctly, the images were downloaded as part of the detached DOM tree creation?

**Comment by Alhadis** [comment]
Ah no, the detached tree doesn't load additional resources until it's appended to the "real" DOM (at which point, every script, image, and stylesheet will be loaded). Funnily enough, though, querying the `<img>` tags of the detached tree *does* cause the referenced image to be loaded (which I wasn't aware of until now).

**Comment by pchaigno** [comment]
Ah, I see. Thanks for the fix and the explanation!
